### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by kirberich**
Hi,

I just went ahead and updated the few bits of python2-specific code (really just one use of urlparse and a couple of simple syntax changes and missing parentheses).

I can't guarantee I caught everything, but at least the bits of the library that I use (which is just the switches bit of the api) seem to work.

Cheers
Rob

### CODE REVIEW

**Comment by kirberich** [comment]
Actually I just realised I did a stupid and just replaced urlparse with urllib.parse, which isn't going to work in python2. I'll try and fix that later today.

**Comment by iancmcc** [comment]
Thanks, I'll check it out immediately!

**Comment by iancmcc** [comment]
Well, the server doesn't work, unsurprisingly; gevent-socketio is incompatible. That's not a dealbreaker, of course. But I couldn't actually get basic CLI usage to detect any of my devices. I'll attempt to debug it further tonight.

**Comment by kirberich** [comment]
ah i think i was just over-optimistic when my basic api use worked. Feel
free to ignore this, it really is very basic. If it gives you a head-start
though, awesome, otherwise I'll try and have a proper look over the weekend.

**Comment by iancmcc** [comment]
#131 adds Python 3 support, using this as a head start. Thanks!

**Comment by kirberich** [comment]
Nice one, thank you Ian!

**Pull request closed without merging**
