### PR TITLE
Initial WEMO Maker support added

### PR DESCRIPTION
**Pull request by logjames**

### CODE REVIEW

**Comment by iancmcc** [comment]
Awesome, I was just about to start this today. Thanks! Will test shortly.

**Comment by logjames** [comment]
It's incomplete...but it allows switch activation. I believe it should be treated as a new class of device since combines a switch and a sensor.

**Comment by iancmcc** [comment]
Yeah, I need to remove the switch/sensor distinction in the code and instead have them as aspects of a device.

**Comment by iancmcc** [comment]
Sorry for the delay. $DAYJOB intervened in a big way. Thanks a lot! It'll be in the 0.7.4 release.

**Comment by logjames** [comment]
No worries…
I am working on CLI maker functions, should have something soon.

**Pull request merged**
